### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by ddfreyne** [minio/homebrew-stable#22]
After `brew install minio/stable/minio`:

```
==> Installing minio from minio/stable
==> Downloading https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2018-03-30T00-38-44Z
Already downloaded: /Users/denis/Library/Caches/Homebrew/minio-20180330003844Z.2018-03-30T00-38-44Z
Error: SHA256 mismatch
Expected: 892b139cd620c48cd1ca5e0c41c1ea7f3320b7ec4fdccebac750efe04dd52480
Actual: cd6a4bb23f3f8ff56ca31d8fdb507c0a5b1e6344a72ff267fbd28bfd1b504db2
Archive: /Users/denis/Library/Caches/Homebrew/minio-20180330003844Z.2018-03-30T00-38-44Z
To retry an incomplete download, remove the file above.
```

**Comment by harshavardhana** [comment]
> After brew install minio/stable/minio:
> 
> ==> Installing minio from minio/stable
> ==> Downloading https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2018-03-30T00-38-44Z
> Already downloaded: /Users/denis/Library/Caches/Homebrew/minio-20180330003844Z.2018-03-30T00-38-44Z
> Error: SHA256 mismatch
> Expected: 892b139cd620c48cd1ca5e0c41c1ea7f3320b7ec4fdccebac750efe04dd52480
> Actual: cd6a4bb23f3f8ff56ca31d8fdb507c0a5b1e6344a72ff267fbd28bfd1b504db2
> Archive: /Users/denis/Library/Caches/Homebrew/minio-20180330003844Z.2018-03-30T00-38-44Z
> To retry an incomplete download, remove the file above.

@ddfreyne just fixed on the master thanks for reporting.
